/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.FilmeDAO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class TelaExibFilme extends javax.swing.JFrame {

    /**
     * Creates new form TelaListaUser
     */
    Usuario usuarioOn;
    public TelaExibFilme(Usuario usuario) {
        initComponents();
        usuarioOn = usuario;
        String[] novostitulos={"Código","Nome","Descrição","Preço"};
        for(int i = 0; i <novostitulos.length; i++){
            jtbUsuarios.getColumnModel().getColumn(i).setHeaderValue (novostitulos[i]);
        }
        jbtCadastro.setVisible(false);
        exibirAdmin(usuarioOn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jbtVoltar = new javax.swing.JButton();
        jbtComprar = new javax.swing.JButton();
        jbtVisu = new javax.swing.JButton();
        jbtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtCadastro = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtVoltar.setText("Sair");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });

        jbtComprar.setText("Comprar");
        jbtComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtComprarActionPerformed(evt);
            }
        });

        jbtVisu.setText("Listar");
        jbtVisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVisuActionPerformed(evt);
            }
        });

        jbtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCodigoActionPerformed(evt);
            }
        });

        jtbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Descrição", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jtbUsuarios);

        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Exibição dos filmes");

        jbtCadastro.setText("Cadastrar");
        jbtCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtVisu)
                        .addGap(18, 18, 18)
                        .addComponent(jbtCadastro))
                    .addComponent(jbtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtComprar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtVoltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtVoltar)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtComprar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtVisu)
                    .addComponent(jbtCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtComprarActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaPagamento tela = new TelaPagamento(usuarioOn);
        tela.setVisible(true);
        try {        
            excluirCodigo(Integer.parseInt(jbtCodigo.getText()));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbtComprarActionPerformed

    private void exibirAdmin(Usuario usuario){
    if(usuario.getUsu().equals("admin")){
        jbtCadastro.setVisible(true);
    } else {
        jbtCadastro.setVisible(false);
    }
    }
    
    private void excluirCodigo(Integer codigo)throws Exception{
    FilmeDAO dao = new FilmeDAO();
         dao.removerDes(codigo);
    }
    
    private void jbtVisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVisuActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jtbUsuarios.getModel();
        model.setRowCount(0);
        
        FilmeDAO desc = new FilmeDAO();
        ArrayList<Filme> listaDesc = new ArrayList<>();
        listaDesc = desc.getDesenhos();
        for (Filme desenho: listaDesc){
            Object [] linha = {
            desenho.getCod(),
            desenho.getNome(),
            desenho.getDesc(),
            desenho.getPreco()
         };
         model.addRow(linha);
         }
        
    }//GEN-LAST:event_jbtVisuActionPerformed

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jbtCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastroActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaAdcFilme tela = new TelaAdcFilme(usuarioOn);
        tela.setVisible(true);
    }//GEN-LAST:event_jbtCadastroActionPerformed

    private void jbtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtCodigoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtCadastro;
    private javax.swing.JTextField jbtCodigo;
    private javax.swing.JButton jbtComprar;
    private javax.swing.JButton jbtVisu;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JTable jtbUsuarios;
    // End of variables declaration//GEN-END:variables
}
