/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.DescricaoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
        

/**
 *
 * @author carlos_js_santos
 */
public class TelaPrincipal extends javax.swing.JFrame {
     private Descricao descricao;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        String[] novostitulos={"Código","Descrição","Potência","Cor"};
        for(int i = 0; i <novostitulos.length; i++){
            jtbDescricaoT.getColumnModel().getColumn(i).setHeaderValue (novostitulos[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbCadastrar = new javax.swing.JButton();
        jlbExcluir = new javax.swing.JButton();
        jlbListar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDescricaoT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtbCodb = new javax.swing.JLabel();
        jtbDescb = new javax.swing.JLabel();
        jtbPotb = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfDescricao = new javax.swing.JTextField();
        jtfPotencia = new javax.swing.JTextField();
        jtbCorb = new javax.swing.JLabel();
        jtfCor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbCadastrar.setText("Cadastrar");
        jlbCadastrar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jlbCadastrarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jlbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbCadastrarActionPerformed(evt);
            }
        });

        jlbExcluir.setText("Excluir");
        jlbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbExcluirActionPerformed(evt);
            }
        });

        jlbListar.setText("Listar");
        jlbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbListarActionPerformed(evt);
            }
        });

        jButton4.setText("Alterar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jtbDescricaoT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbDescricaoT);

        jLabel1.setText("Cadastro de Carros");

        jtbCodb.setText("Código:");

        jtbDescb.setText("Descrição:");

        jtbPotb.setText("Potencia:");

        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });

        jtfDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDescricaoActionPerformed(evt);
            }
        });

        jtbCorb.setText("Cor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jlbCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jlbListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jtbCodb)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbPotb)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jtbCorb)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtbDescb)
                        .addGap(326, 326, 326))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(138, 138, 138))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbCodb)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbDescb)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbPotb)
                    .addComponent(jtfPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbCorb)
                    .addComponent(jtfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCadastrar)
                    .addComponent(jlbExcluir)
                    .addComponent(jlbListar)
                    .addComponent(jButton4))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbCadastrarActionPerformed
        // TODO add your handling code here:
        DescricaoDAO descricaoDAO = new DescricaoDAO();
        String desc = jtfDescricao.getText().trim();
        String pot = jtfPotencia.getText().trim();
        String cor = jtfCor.getText().trim();
    
    if (!desc.isEmpty() && !pot.isEmpty() && !cor.isEmpty()) {
        Descricao descricao = descricaoDAO.adicionar(desc, pot, cor);
        if (descricao != null) {
            JOptionPane.showMessageDialog(null, "Descrição adicionada com sucesso.");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao adicionar a descrição.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");
    }

    }//GEN-LAST:event_jlbCadastrarActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jlbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbExcluirActionPerformed
        // TODO add your handling code here:
           DescricaoDAO dao = new DescricaoDAO();
        try {
            int numero = Integer.parseInt(jtfCodigo.getText());
            dao.removerCad(numero);
            JOptionPane.showMessageDialog(null, "Carro Excluído com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro para excluir o carro");
        }
                                           
    }//GEN-LAST:event_jlbExcluirActionPerformed

    private void jlbCadastrarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jlbCadastrarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbCadastrarAncestorAdded

    private void jtfDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescricaoActionPerformed

    private void jlbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbListarActionPerformed
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) jtbDescricaoT.getModel();
        model.setRowCount(0);
        
        DescricaoDAO cadcarros = new DescricaoDAO();
        ArrayList<Descricao> listacadcarros = new ArrayList<>();
        listacadcarros = cadcarros.getDescricoes();
        for (Descricao descricao: listacadcarros){
            Object [] linha = {
            descricao.getCod(),
            descricao.getDesc(),
            descricao.getPot(),
            descricao.getCor()
         };
         model.addRow(linha);
         }
              
    }//GEN-LAST:event_jlbListarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                if (!jtfCodigo.getText().isBlank()) {
    if (!jtfCor.getText().isBlank()) {
        DescricaoDAO Desc = new DescricaoDAO();
        try {
            Desc.alterarDesc(Integer.parseInt(jtfCodigo.getText()), jtfCor.getText());
            JOptionPane.showMessageDialog(null, "Cor alterada com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar a Cor ");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Preencha o campo Cor");
    }
} else {
    JOptionPane.showMessageDialog(null, "Preencha o campo código");
}

   
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jlbCadastrar;
    private javax.swing.JButton jlbExcluir;
    private javax.swing.JButton jlbListar;
    private javax.swing.JLabel jtbCodb;
    private javax.swing.JLabel jtbCorb;
    private javax.swing.JLabel jtbDescb;
    private javax.swing.JTable jtbDescricaoT;
    private javax.swing.JLabel jtbPotb;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfCor;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfPotencia;
    // End of variables declaration//GEN-END:variables
}
